#!/usr/bin/env bash

################################################################################
#
#    con-test
#    This is part of the con-test framework
#
#    Copyright (C) 2018  Stefan Venz
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
################################################################################

set -o pipefail -o noclobber

# import common funcitons and variables
source ./commons

VERBOSE=n

LOG_PATH="con-test_logs"

SUDO=''

# create a file on remote system to stop file collection
#
# Arguments:
# side - client or server side to stop
#
stop_file_collect()
{
	side=$1
	auth=$(check_auth $side)

	if [[ "$side" == "$CLIENT" ]]; then
		ip=$CLIENT_IP
		user=$CLIENT_USER
		passwd=${CLIENT_PASSWORD:-"none"}
		cert=${CLIENT_CERTIFICATE:-"none"}
	else
		ip=$SERVER_IP
		user=$SERVER_USER
		passwd=${SERVER_PASSWORD:-"none"}
		cert=${SERVER_CERTIFICATE:-"none"}
	fi

	if [[ "$auth" == "$PASSWD" ]]; then
		sshpass -p $passwd ssh ${user}@${ip} \
			'touch /tmp/stop'
	else
		ssh -i $cert ${user}@${ip} \
			'touch /tmp/stop'
	fi
}

add_timestamp()
{
	time=$1
	file=$2
	run=$3
	append=$4

	while usleep $time
	do
		if [ -f '/tmp/stop' ]; then
			break
		fi
		cat $file | while IFS= read -r line; do printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S.%N')" "$line"; done
	done
}

# get a single file from target
#
# Arguments:
# ip  	-	ip address to optain file from
# user -	username for login
# passwd -	password for user
# cert -	certificate for login
# auth -	use password or cert for login
# file -	file to get from system
# run -		run number
# log -		log path
# side -	client or server side
# time -	time inbetween file reads
#
get_file()
{
	file=$1 && shift
	collect_args=($@)
	ip=${collect_args[0]}
	user=${collect_args[1]}
	passwd=${collect_args[2]}
	cert=${collect_args[3]}
	run=${collect_args[4]}
	log=${collect_args[5]}
	side=${collect_args[6]}
	time=${collect_args[7]}
	auth=${collect_args[8]}

	if [[ "$side" == "$CLIENT" ]]; then
		append='client'
	else
		append='server'
	fi

	if [[ "$auth" == "$PASSWD" ]]; then
		sshpass -p "$passwd" ssh ${user}@${ip} 'if [[ -f /tmp/stop ]]; then rm /tmp/stop; fi'
		sshpass -p "$passwd" ssh ${user}@${ip} \
			"$(declare -f add_timestamp); \
			add_timestamp $time $file $run $append" >> \
			${log}/$(basename $file)_${run}_${append}.log

	else
		ssh -i $cert ${user}@${ip} 'if [[ -f /tmp/stop ]]; then rm /tmp/stop; fi'
		ssh -i $cert ${user}@${ip} \
			"$(declare -f add_timestamp); \
			add_timestamp $time $file $run $append" >> \
			${log}/$(basename $file)_${run}_${append}.log
	fi
}
export -f get_file

# get file from remote system
#
# Arguemtns:
# file - file to collect from remote system
# side - collect from client or server
# time - time inbetween file reads
#
collect_files()
{
	run=$1
	side=$2
	time=$3
	config_path=$4
	auth=$(check_auth $side)

	export $LOG_PATH
	if (( $side == $CLIENT )); then
		declare -a collect_arg=("$CLIENT_IP"
					"$CLIENT_USER"
					"${CLIENT_PASSWORD:-"none"}" 
					"${CLIENT_CERTIFICATE:-"none"}")
	else
		declare -a collect_arg=("$SERVER_IP"
					"$SERVER_USER"
					"${SERVER_PASSWORD:-"none"}"
					"${SERVER_CERTIFICATE:-"none"}")
	fi
	collect_arg=("${collect_arg[@]}"
		     "$run"
		     "$LOG_PATH"
		     "$side"
		     "$time"
		     "$auth")

	for file in ${FILES[@]};
	do
		get_file $file ${collect_arg[@]} &
	done
}

# check dependencies on wifi nodes
#
check_remote_deps()
{
	printf "${INFO} Checking dependencies on ${SERVER_IP}"

	printf "${INFO} Checking dependencies on ${CLIENT_IP}"
}

# start iperf server
#
# Arguments:
# run - number of current test, starting with 1
# side - where to start iperf:  0 for client, 1 for server
#
start_iperf()
{
	run="$1"
	side=$2

	auth=$(check_auth $side)

	# set parameter for client or server
	if [[ "$side" == "$CLIENT" ]]; then
		log_name="con-test-client-run-${run}-$(date +%F-%H-%M-%S).log"
		ip=$CLIENT_IP
		user=$CLIENT_USER
		param="-c $SERVER_WIFI_IP "
		if [ -n "${IPERF_PARAM_CLIENT[${run} - 1]}" ]; then
			param="${IPERF_PARAM_CLIENT[${run} - 1]} $param"
		fi

		passwd=$CLIENT_PASSWORD
		cert=$CLIENT_CERTIFICATE

	else
		log_name="con-test-server-run-${run}-$(date +%F-%H-%M-%S).log"
		ip=$SERVER_IP
		user=$SERVER_USER
		param="-s"
		if [ -n "${IPERF_PARAM_SERVER[${run} - 1]}" ]; then
			param="${param} ${IPERF_PARAM_SERVER[${run} - 1]}"
		fi
		passwd=$SERVER_PASSWORD
		cert=$SERVER_CERTIFICATE
	fi

	printf "${INFO} Attenuation parameter: ${ATTENUATOR_PARAMS[${run} - 1]}" > \
							${LOG_PATH}/${log_name}
	printf "${INFO} Iperf parameter: ${param}" >> ${LOG_PATH}/${log_name}

	# use cert or password for authentication
	if [[ "$auth" == "$PASSWD" ]]; then
		iperf_pid=$(sshpass -p "$passwd" \
			    ssh ${user}@${ip} "ps" \
			    | awk '/[i]perf/{ print $1 }')
		if [ -n "$iperf_pid" ]; then
			ret=$(sshpass -p "$passwd" \
			      ssh ${user}@${ip} \
			      "kill -9 $iperf_pid")
			check_ret_val "$?" "Could not kill iperf: $iperf_pid - $ret"
		fi

		ret=$(nohup sshpass -p "$passwd" \
		      ssh ${user}@${ip} \
		      "iperf3 $param" >> ${LOG_PATH}/${log_name} &)
		check_ret_val $? "Failed to start iperf with ${param} on ${ip}: $ret"
	else
		iperf_pid=$(ssh -i $cert \
			    ${user}@${ip} "ps" \
			    | awk '/[i]perf/{ print $1 }')
		if [ -n "$iperf_pid" ]; then
			ret=$(ssh -i $cert \
			      ${user}@${ip} "kill -9 $iperf_pid")
			check_ret_val "$?" "Could not kill iperf: $iperf_pid - $ret"
		fi

		ret=$(ssh -i $cert \
		      ${user}@${ip} \
		      "iperf3 $param" >> ${LOG_PATH}/${log_name} &)
		check_ret_val $? "Failed to start iperf with ${param}on ${ip}: $ret"
	fi
}

# start attenuators, get the attenuation up
#
# Arguments:
# params - parameters for the attenuator programm
#
start_antennuator()
{
	params="$@"
	$SUDO $ATTENUATOR_PATH $params
	check_ret_val $? "Could not start the attenuation programm"
}

# copy package to device and update it
#
# Arguments:
# u_name - user name on remote host
# ip - update package on this host
# path - path to package on current host include package name
# key - path to identity file
#
update_package()
{
	u_name="${PARAMS[0]}"
	ip="${PARAMS[1]}"
	path="${PARAMS[2]}"
	pw="${PARAMS[3]}"
	key="${PARAMS[4]}"

	if [ ! -f "$path" ]; then
		printf "${ERROR} ${path} does not exist or cannot be accessed"
		return $FAILURE
	fi

	pkg_name=$(basename "$path")
	if [ -n "$key" ]; then
		scp -i $key ${path} ${u_name}@${ip}:/tmp/
		check_ret_val $? "Failed to copy $pkg_name to $ip"

		ssh -i $key ${u_name}@${ip} "opkg update" 1>/dev/null 2>&1

		ret=$(ssh -i $key ${u_name}@${ip} \
		      "opkg remove --force-depends $pkg_name" 1>/dev/null 2>&1)
		check_ret_val $? "ssh on $ip returned $?: Failed to run opkg remove"

		ret=$(ssh -i $key ${u_name}@${ip} \
		      "opkg install --force-reinstall /tmp/${pkg_name}" \
		      1>/dev/null 2>&1)
		check_ret_val $? "ssh on $ip returned $?: Failed to run opkg install"
	elif [ -n "$pw" ]; then
		sshpass -p $pw scp ${path} ${u_name}@${ip}:/tmp/
		check_ret_val $? "Failed to copy $pkg_name to $ip"

		sshpass -p $pw ssh ${u_name}@${ip} "opkg update" \
			1>/dev/null 2>&1

		ret=$(sshpass -p $pw ssh ${u_name}@${ip} \
			"opkg remove --force-depends $pkg_name" \
			1>/dev/null 2>&1)
		check_ret_val $? "ssh on $ip returned $?: Failed to run opkg remove"

		ret=$(sshpass -p $pw ssh ${u_name}@${ip} \
		      "opkg install --force-reinstall /tmp/${pkg_name}" \
		      1>/dev/null 2>&1)
		check_ret_val $? "ssh on $ip returned $?: Failed to run opkg install"
	fi

	return $SUCCESS
}

# print information about this script
#
call_help()
{
	printf "con-test help:\n\n"
	printf "\t -c, --config:\t provide path to conn-test.conf, default ./conn-test.conf \n\n"
	printf "\t -h, --help:\t call this overview\n\n"
	printf "\t -o, --output\t path to log file to store output, default ./conn-test.log \n\n"
	printf "\t -v, --verbose\t output more information during a run\n"
	printf "\t -V, --version\t print con-test version\n"
}

# main function
#
# Arguments:
# args - command line arguments
#
main()
{
	args=$@
	options=c:hmo:vV
	loptions=config:,help,monitor,output:,verbose,version
	mon=$OFF
	
	config_path="con-test.conf"
	LOG_PATH="con-test_logs"

	
	! parsed=$(getopt --options=$options --longoptions=$loptions --name "$0" -- $args)
	if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
	    exit $FAILURE
	fi
	eval set -- "$parsed"

	while true; do
		case "$1" in
			-c | --config)
				config_path=$2
				export config_path
				shift 2
				;;
			-h | --help)
				call_help
				exit $SUCCESS
				;;
			-m | --mon)
				mon=$OFF
				shift
				;;
			-o | --output)
				LOG_PATH=$2
				shift 2
				;;
			-v | --verbose)
				VERBOSE=y
				shift
				;;
			-V | --version)
				print_version
				exit $SUCCESS
				;;
			--)
				shift
				break
				;;
			*)
				break
				;;
		esac
	done

	printf "${INFO} Starting conn-test script\n"
	printf "\t\tUsing ${config_path}\n"
	printf "\t\tUsing ${LOG_PATH}/\n"
	if [ ! -f "$config_path" ]; then
		printf "${ERROR} ${config_path} does not exist, or can not be accessed"
		exit $FAILURE
	fi
	export $LOG_PATH
	source ${config_path}

	check_dependecies

	mkdir -p $LOG_PATH

	for i in $(seq 1 ${NR_RUNS}); do
		printf "${INFO} Starting test run $i with parameters:"
		printf " ${ATTENUATOR_PARAMS[${i} - 1]}\n"
		time="${TIME[${i} - 1]:-100000}"

		if [ -n "${UPDATE_PKG[${i} - 1]}" ]; then
			printf "${INFO} update package: ${UPDATE_PKG[${i} - 1]}"

			PARAMS=("$SERVER_USER" "$SERVER_IP" \
				"${UPDATE_PKG[$i - 1]}" "$SERVER_PASSWORD" \
				"$SERVER_CERTIFICATE")
			update_package $PARAMS
			unset $PARAMS

			PARAMS=("$CLIENT_USER" "$CLIENT_IP"
				"${UPDATE_PKG[${i} - 1]}" "$CLIENT_PASSWORD" \
				"$CLIENT_CERTIFICATE")
			update_package $PARAMS
			unset $PARAMS
		fi

		if [[ "$mon" == "$ON" ]]; then
			bash wireless_monitor -o $LOG_PATH -c $config_path &
		fi

		#start measurement
		start_iperf "$i" "$SERVER"
		start_iperf "$i" "$CLIENT"

		collect_files "$i" $CLIENT "$time" "$config_path" &
		collect_files "$i" $SERVER "$time" "$config_path" &

		sleep 3

		start_antennuator ${ATTENUATOR_PARAMS[${i} - 1]}

		sleep 2

		stop_file_collect "$CLIENT"
		stop_file_collect "$SERVER"

		if [[ "$mon" == "$ON" ]]; then
			touch /tmp/stop_mon
		fi
	done
}

main $@
