#!/usr/bin/env bash

################################################################################
#
#    wifi-monitor
#    This is part of the con-test framework
#
#    Copyright (C) 2019  Stefan Venz
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
################################################################################

source ./commons

LOG_PATH="con-test_logs"
SUDO=''

# set interface to monitor mode to collect traffic with tcpdump
#
# Aguments:
# interface - interface to use for monitor mode
#
set_interface_to_monitor()
{
	interface=$1
	ret=$SUCCESS

	$SUDO ifconfig $interface down
	$SUDO ifconfig $interface mode Monitor
	$SUDO ifconfig $interface up
}

check_monitor()
{
	interface=$1
	passwd=$2
	cert=$3
	user=$4
	ip=$5
	auth=$6

	if (( $auth == $PASSWD )); then
		if [[ "$(sshpass -p "$passwd" ssh ${user}@${ip} \
			iw dev | awk "/${interface}/{nr[NR+5]}; NR in nr" | \
			awk '{print $2}')" == "monitor" ]]; then
				ret=$SUCCESS
		else
			printf "${WARNING} $interface is not in monitor mode\n"
			ret=$FAILURE
		fi
	else
		if [[ "$(ssh -i ${cert} ${user}@${ip} \
			iw dev | awk "/${interface}/{nr[NR+5]}; NR in nr" | \
			awk '{print $2}')" == "monitor" ]]; then
				ret=$SUCCESS
		else
			printf "${WARNING} $interface is not in monitor mode\n"
			ret=$FAILURE
		fi
	fi
	return $ret
}

# start tcp dump
#
# Arguemnts:
# interface - use this interface for tcpdump
# time - amount of seconds tcpdump runs
# side - Client or server side to start tcpdump
#
start_tcpdump()
{
	interface=$1
	time=$2
	side=$3
	auth=$(check_auth $side)

	if (( $side == $CLIENT )); then
		file_name="client_con-test-tcpdump-$(date +%F-%H-%M-%S).log"
		passwd=$CLIENT_PASSWORD
		cert=$CLIENT_CERTIFICATE
		ip=$CLIENT_IP
		user=$CLIENT_USER
	else
		file_name="server_con-test-tcpdump-$(date +%F-%H-%M-%S).log"
		passwd=$SERVER_PASSWORD
		cert=$SERVER_CERTIFICATE
		ip=$SERVER_IP
		user=$SERVER_USER
	fi

	if (( $auth == $PASSWD )); then
		check_monitor $interface $passwd $cert $user $ip $auth
		check_ret_val $? "Please set the interface to monitor mode"

		ret=$(nohup sshpass -p "$passwd" ssh ${user}@${ip} \
			     "timeout $time tcpdump -w ${LOG_PATH}/$file_name \
			     -i $interface" >> ${LOG_PATH}/${file_name} &)
		check_ret_val $? "something went wrong starting tcpdump on $ip"
	else
		check_monitor $interface $passwd $cert $user $ip $auth
		ret=$(nohup ssh -i ${cert} ${user}@${ip} \
		      "timeout $time tcpdump -w ${LOG_PATH}/${file_name} \
		      -i $interface" >> ${LOG_PATH}/${file_name} &)
		check_ret_val $? "something went wrong starting tcpdump on $ip"

	fi
}

# print information about this script
#
call_help()
{
	printf "con-test help:\n\n"
	printf "\t -c, --config:\t provide path to conn-test.conf, default ./conn-test.conf \n\n"
	printf "\t -h, --help:\t call this overview\n\n"
	printf "\t -i, --interface\t  monitor interface\n\n"
	printf "\t -o, --output\t path to log file to store output, default ./conn-test.log \n\n"
	printf "\t -t, --time\t time to run tcpdump\n"
	printf "\t -V, --version\t print con-test version\n"
}

# main function
#
# Arguments:
# args - command line arguments
#
main()
{
	args=$@
	time=0
	interface=''

	test_get_opt

	options=c:hmo:t:V
	loptions=config:,help,monitor,output:,time:,version
	config_path="con-test.conf"

	! parsed=$(getopt --options=$options --longoptions=$loptions --name "$0" -- $args)
	if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
		exit $FAILURE
	fi

	eval set -- "$parsed"

	while true; do
		case "$1" in
			-c | --config)
				config_path=$2
				shift 2
				;;
			-h | --help)
				call_help
				exit $SUCCESS
				;;
			-i | --interface)
				interface=$2
				shift 2
				;;
			-o | --output)
				LOG_PATH=$2
				shift 2
				;;
			-t | --time)
				TIME=$2
				shift 2
				;;
			-V | --version)
				print_version
				exit $SUCCESS
				;;
			--)
				shift
				break
				;;
			*)
				break
				;;
		esac
	done

	if [ -z $interface ]; then
		printf "${ERROR} Please provide an interface for monitoring\n"
		exit $FAILURE
	fi

	printf "${INFO} Starting wireless monitor\n"
	printf "\t\tUsing config ${config_path}\n"
	printf "\t\tUsing logpath ${LOG_PATH}\n"

	if [ ! -f "${config_path}" ]; then
		printf "${ERROR} ${config_path} does not exist or can not be accessed"
		exit $FAILURE
	fi

	source $config_path

	check_dependecies

	mkdir -p $LOG_PATH

	# check_monitor $interface

	printf "${INFO} starting monitoring $interface on $CLIENT_IP\n"
	ret=start_tcpdump $interface $time $CLIENT
	check_ret_val $ret "Failed to start tcpdump on $CLIENT_IP $interface"

	printf "${INFO} starting monitoring $interface on $SERVER_IP\n"
	ret=start_tcpdump $interface $time $SERVER
	check_ret_val $ret "Failed to start tcpdump on $SERVER_IP $interafce"
}

main $@

